name: Build and test SDKs

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up git user
        uses: fregante/setup-git-user@v1
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install project dependencies
        run: npm ci
      - name: Run test suite
        run: npm run test
