name: Docs and API check

on:
  pull_request:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
  check-pkglock:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Run full npm install
        run: npm install
      - name: Check package-lock for diffs
        id: diff_pkg_lock
        run: git diff --exit-code --name-only package-lock.json
      #   continue-on-error: true
      # - if: ${{ steps.diff_pkg_lock.outcome == 'failure' }}


